CREATE TABLE Person
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   varchar NOT NULL UNIQUE,
    dateOfBirth DATE    NOT NULL

);

CREATE TABLE Book
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     varchar NOT NULL,
    author    varchar NOT NULL,
    isbn      varchar,
    taken_at  DATE,
    person_id int     REFERENCES Person (id) ON DELETE SET NULL
);

-- ALTER TABLE Book ADD COLUMN taken_at  DATE;
-- ALTER TABLE Book DROP COLUMN taken_at;

ALTER TABLE Person ADD COLUMN date_of_birth  DATE NOT NULL ;
ALTER TABLE Person DROP COLUMN dateofbirth;


-- spring.mvc.hiddenmethod.filter.enabled=true